import "./globals.css";
import Link from "next/link";

export const metadata = { title: "Pulse & Plug | Premium Health, Recovery & Wellness Systems", description: "Premium health appliances, therapeutic recovery equipment, and wellness essentials." };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="en"><body><div className="topbar"><div className="container"><span>Free white-glove delivery on Advanced Recovery Systems</span><div className="toplinks"><a href="tel:+17864066937">☎ +1 786-406-6937</a><a href="mailto:pulsendplug@gmail.com">✉ pulsendplug@gmail.com</a></div></div></div><header className="header"><div className="container nav"><Link href="/"><img className="logo" src="https://pulse-plug-e-commerce-website.vercel.app/images/pndp.png" alt="Pulse & Plug Relief & Power"/></Link><nav className="links"><Link href="/">Home</Link><Link href="/shop">Shop</Link><Link href="/contact">Contact</Link></nav><div className="actions"><button className="iconbtn" aria-label="Dark mode">◔</button><Link className="iconbtn" href="/cart" aria-label="Cart">▢</Link><button className="iconbtn mobile" aria-label="Menu">☰</button></div></div></header><main>{children}</main><Footer/></body></html>
}

function Footer(){return <footer className="footer"><div className="container footerGrid"><div><img className="logo" src="https://pulse-plug-e-commerce-website.vercel.app/images/pndp.png" alt="Pulse & Plug"/><p>Premium health appliances, therapeutic recovery equipment, and wellness consumables for a healthier, more comfortable life.</p></div><div><h4>Explore</h4><ul><li><Link href="/">Home</Link></li><li><Link href="/shop">Shop</Link></li><li><Link href="/contact">Contact</Link></li><li><Link href="/cart">Cart</Link></li></ul></div><div><h4>Collections</h4><ul><li><Link href="/shop#advanced-recovery-systems">Advanced Recovery Systems</Link></li><li><Link href="/shop#targeted-therapy-devices">Targeted Therapy Devices</Link></li><li><Link href="/shop#daily-essentials">Daily Wellness Essentials</Link></li></ul></div><div><h4>Contact</h4><ul><li><a href="tel:+17864066937">+1 786-406-6937</a></li><li><a href="mailto:pulsendplug@gmail.com">pulsendplug@gmail.com</a></li><li>Serving the US, Canada, UK & Australia</li></ul></div></div><div className="container subfooter"><span>Secure, encrypted checkout · Visa · Mastercard · Amex · Apple Pay · Google Pay · Affirm · Klarna</span><span>© 2026 Pulse & Plug. All rights reserved.</span></div></footer>}
