import { neon } from '@neondatabase/serverless'

export type Product = { id:string; name:string; slug:string; category:string; description:string; price:number; businessPrice:number|null; imageUrl:string; active:boolean; sortOrder:number; createdAt:string; updatedAt:string }
function getSql(){const url=process.env.DATABASE_URL||process.env.POSTGRES_URL;if(!url)throw new Error('DATABASE_URL is not configured');return neon(url)}
export async function ensureProductsTable(){const sql=getSql();await sql`CREATE EXTENSION IF NOT EXISTS pgcrypto`;await sql`CREATE TABLE IF NOT EXISTS products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, category TEXT NOT NULL DEFAULT 'Uncategorized', description TEXT NOT NULL DEFAULT '', price NUMERIC(12,2) NOT NULL DEFAULT 0, business_price NUMERIC(12,2), image_url TEXT NOT NULL DEFAULT '', active BOOLEAN NOT NULL DEFAULT TRUE, sort_order INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`}
function mapProduct(row:any):Product{return{id:row.id,name:row.name,slug:row.slug,category:row.category,description:row.description,price:Number(row.price),businessPrice:row.business_price==null?null:Number(row.business_price),imageUrl:row.image_url,active:Boolean(row.active),sortOrder:Number(row.sort_order),createdAt:row.created_at,updatedAt:row.updated_at}}
export async function listProducts(includeInactive=false){await ensureProductsTable();const sql=getSql();const rows=includeInactive?await sql`SELECT * FROM products ORDER BY sort_order ASC, created_at DESC`:await sql`SELECT * FROM products WHERE active=TRUE ORDER BY sort_order ASC, created_at DESC`;return rows.map(mapProduct)}
export async function getProductBySlug(slug:string){await ensureProductsTable();const sql=getSql();const rows=await sql`SELECT * FROM products WHERE slug=${slug} AND active=TRUE LIMIT 1`;return rows[0]?mapProduct(rows[0]):null}
export async function createProduct(input:{name:string;slug:string;category:string;description:string;price:number;businessPrice?:number|null;imageUrl:string;sortOrder?:number}){await ensureProductsTable();const sql=getSql();const rows=await sql`INSERT INTO products (name,slug,category,description,price,business_price,image_url,sort_order) VALUES (${input.name},${input.slug},${input.category},${input.description},${input.price},${input.businessPrice??null},${input.imageUrl},${input.sortOrder??0}) RETURNING *`;return mapProduct(rows[0])}
export async function deleteProduct(id:string){await ensureProductsTable();const sql=getSql();await sql`DELETE FROM products WHERE id=${id}`}
export async function updateProduct(id:string,input:Partial<{name:string;slug:string;category:string;description:string;price:number;businessPrice:number|null;imageUrl:string;active:boolean;sortOrder:number}>){await ensureProductsTable();const sql=getSql();const current=await sql`SELECT * FROM products WHERE id=${id} LIMIT 1`;if(!current[0])throw new Error('Product not found');const c=current[0];const rows=await sql`UPDATE products SET name=${input.name??c.name},slug=${input.slug??c.slug},category=${input.category??c.category},description=${input.description??c.description},price=${input.price??c.price},business_price=${input.businessPrice===undefined?c.business_price:input.businessPrice},image_url=${input.imageUrl??c.image_url},active=${input.active??c.active},sort_order=${input.sortOrder??c.sort_order},updated_at=NOW() WHERE id=${id} RETURNING *`;return mapProduct(rows[0])}
