export type Product={slug:string;name:string;price:number;businessPrice:number;category:string;description:string;image:string;source:string};
const base='https://pulse-plug-e-commerce-website.vercel.app/images/products/';
const raw:[string,string,number,number,string,string,string,string][]=[
['premium-rubber-cork-yoga-mat','Premium Rubber/Cork Yoga Mat',85,60,'Studio Essentials','Eco friendly, high grip mat built for daily class use. A retail add on your members will want to take home.','yoga-mat.png','Yoga & Fitness Studios'],
['resistance-band-set-5-piece','Resistance Band Set (5 Piece)',52,35,'Studio Essentials','Compact, multi resistance set perfect for warm ups, strength add ons, or retail sale at the front desk.','resistance-bands.png','Yoga & Fitness Studios'],
['studio-grade-foam-roller','Studio Grade Foam Roller',60,47,'Studio Essentials','The ultimate recovery tool for pre and post class routines. A top selling self checkout retail item.','foam-roller.png','Yoga & Fitness Studios'],
['premium-percussion-massage-gun','Premium Percussion Massage Gun',119,80,'Targeted Therapy Devices','Deep tissue recovery tool clients can use in studio, rent, or purchase to take home.','percussion-massage-gun.png','Yoga & Fitness Studios'],
['commercial-pilates-reformer','Commercial Pilates Reformer',4500,3200,'Studio Essentials','Studio grade reformer for group reformer classes. Most studios order 4 to 8 units to outfit a room.','pilates-reformer.png','Yoga & Fitness Studios'],
['ladder-barrel-spine-corrector','Ladder Barrel / Spine Corrector',650,500,'Studio Essentials','Adds variety to reformer programming. A natural add on once a studio is equipped with reformers.','ladder-barrel.png','Yoga & Fitness Studios'],
['4d-ai-zero-gravity-massage-chair','4D AI-Powered Zero-Gravity Massage Chair',9500,4900,'Advanced Recovery Systems','A flagship recovery lounge centerpiece that turns your studio into a destination, not just a class.','4d-massage-chair.png','Yoga & Fitness Studios; Luxury & Office Space; Chiropractic & Physical Therapy Clinics'],
['far-infrared-jade-thermal-massage-bed','Full-Body Far-Infrared Jade Thermal Massage Bed',3800,2300,'Advanced Recovery Systems','Deep radiant heat therapy for a dedicated recovery room.','jade-thermal-bed.png','Yoga & Fitness Studios; Luxury & Office Space; Chiropractic & Physical Therapy Clinics'],
['luxury-memory-foam-air-pressure-mattress-system','Luxury Memory Foam Air-Pressure Mattress System',950,700,'Advanced Recovery Systems','A restorative rest station for a recovery corner or quiet room.','air-pressure-mattress.png','Yoga & Fitness Studios; Luxury & Office Space; Chiropractic & Physical Therapy Clinics'],
['compact-commercial-infrared-sauna','Compact Commercial Infrared Sauna',4500,3300,'Advanced Recovery Systems','A high value amenity that supports premium membership tiers or drop in day passes.','infrared-sauna.png','Yoga & Fitness Studios; Luxury & Office Space'],
['commercial-cold-plunge-tub','Commercial Cold Plunge Tub',4000,2800,'Advanced Recovery Systems','Pairs with the sauna for contrast therapy, a fast growing member expectation in premium studios.','cold-plunge.png','Yoga & Fitness Studios; Luxury & Office Space'],
['premium-bamboo-acupressure-mat-pillow-set','Premium Bamboo Acupressure Mat & Pillow Set',75,62,'Daily Wellness Essentials','Affordable retail add on for members looking for at home recovery tools.','acupressure-mat.png','Yoga & Fitness Studios; Luxury & Office Space'],
['manual-chiropractic-treatment-table','Manual Chiropractic Treatment Table',1500,750,'Clinical & Treatment Equipment','Reliable adjustment table built for daily clinical use. A solid entry point for a new or growing practice.','manual-chiro-table.png','Chiropractic & Physical Therapy Clinics'],
['power-chiropractic-treatment-table','Power Chiropractic Treatment Table',5000,2500,'Clinical & Treatment Equipment','Motorized, height adjustable table for high volume practices running back to back patients.','power-chiro-table.png','Chiropractic & Physical Therapy Clinics'],
['red-light-therapy-wall-panel','Professional-Grade Red Light Therapy Wall Panel',2200,0,'Advanced Recovery Systems','Clinical grade cellular repair at home.','red-light-panel.png','Existing Pulse & Plug Catalog'],
['sequential-compression-recovery-boots','Pneumatic Sequential Compression Recovery Boots',1100,0,'Advanced Recovery Systems','Flush fatigue from tired, heavy legs.','compression-boots.png','Existing Pulse & Plug Catalog'],
['3d-heated-shiatsu-foot-calf-massager','3D Heated Shiatsu Foot and Calf Massager',450,0,'Targeted Therapy Devices','Spa grade relief for tired feet and calves.','shiatsu-foot-massager.png','Existing Pulse & Plug Catalog'],
['smart-electric-cervical-traction-collar','Smart Electric Cervical Traction Neck Collar',320,0,'Targeted Therapy Devices','Gentle traction for neck relief.','cervical-traction-collar.png','Existing Pulse & Plug Catalog'],
['heated-temple-eye-massager','App-Controlled Heated Temple & Eye Massager',200,0,'Targeted Therapy Devices','Melt away eye strain and tension headaches.','eye-temple-massager.png','Existing Pulse & Plug Catalog'],
['heated-shiatsu-shoulder-wrap','Ergonomic Heated Shiatsu Shoulder Wrap',150,0,'Targeted Therapy Devices','Wrap around relief for neck and shoulders.','shoulder-wrap.png','Existing Pulse & Plug Catalog'],
['weighted-deep-pressure-therapy-blanket','Weighted Deep-Pressure Therapy Blanket',120,0,'Targeted Therapy Devices','Calming, grounding deep pressure comfort.','weighted-blanket.png','Existing Pulse & Plug Catalog'],
['vibrating-foam-roller','Vibrating Foam Roller for Myofascial Release',90,0,'Daily Wellness Essentials','Vibration powered myofascial release.','vibrating-foam-roller.png','Existing Pulse & Plug Catalog'],
['arnica-menthol-recovery-balm','Intensive Organic Arnica & Menthol Recovery Balm',60,0,'Daily Wellness Essentials','Cooling, targeted muscle relief.','arnica-balm.png','Existing Pulse & Plug Catalog'],
['eucalyptus-massage-oil','Cold-Pressed Organic Eucalyptus Massage Oil',45,0,'Daily Wellness Essentials','Aromatic, nourishing massage oil.','eucalyptus-oil.png','Existing Pulse & Plug Catalog'],
['organic-soya-milk-protein-powder','Premium Non-GMO Organic Soya Milk Protein Powder',40,0,'Daily Wellness Essentials','Clean plant protein for recovery.','soya-protein.png','Existing Pulse & Plug Catalog'],
['adaptogenic-stress-relief-tea','High-Grade Adaptogenic Stress-Relief Tea Blend',35,0,'Daily Wellness Essentials','A calming ritual in every cup.','stress-relief-tea.png','Existing Pulse & Plug Catalog'],
['himalayan-pink-salt-wellness-soak','Himalayan Pink Salt Wellness Soak (Large)',30,0,'Daily Wellness Essentials','Mineral rich soak for tired bodies.','himalayan-soak.png','Existing Pulse & Plug Catalog'],
['silicone-gua-sha-facial-kit','Silicone Gua Sha & Facial Massage Tool Kit',25,0,'Daily Wellness Essentials','Gentle facial recovery ritual.','gua-sha-kit.png','Existing Pulse & Plug Catalog'],
['ultrasonic-essential-oil-diffuser','Ultrasonic Essential Oil Diffuser',20,0,'Daily Wellness Essentials','Transform any room into a calm retreat.','oil-diffuser.png','Existing Pulse & Plug Catalog']
];
export const products:Product[]=raw.map(([slug,name,price,businessPrice,category,description,image,source])=>({slug,name,price,businessPrice,category,description,image:base+image,source}));
